version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "usebitwardenplease"
      MYSQL_DATABASE: "java-app"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "mentat"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "usebitwardenplease"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "mentat"
    restart: always
    container_name: phpmyadmin

volumes:
  mysql-data:
    driver: local
